# Generated by Django 4.0.6 on 2024-04-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100, null=True)),
                ('ano', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='fotos_bandas/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Song',
            new_name='Musica',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='year',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='duration',
            new_name='duracao',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='album',
            name='band',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.AddField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bandas.banda'),
        ),
    ]
